[package]
name = "rust-eco"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10.0", features = ["canvas", "tokio", "debug"] }
tokio = { version = "1.0", features = ["time"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"